export const BUTTONS: {
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: number;
    8: number;
    9: number;
    10: number;
    11: number;
    12: number;
    13: number;
    14: number;
    15: string;
    16: string;
    17: string;
    18: string;
    19: string;
    20: string;
    21: string;
    22: string;
    23: string;
    24: string;
    25: string;
    26: string;
    27: number;
    28: number;
    29: number;
    30: number;
    31: number;
    32: number;
    33: number;
    34: number;
    35: number;
    36: number;
    37: number;
    38: number;
    39: number;
    40: number;
    41: number;
};
export const CONNECTION_TIMEOUT: 3000;
export namespace COMMANDS {
    let BUTTON_PRESS: number;
    let KNOB_ROTATE: number;
    let SET_COLOR: number;
    let SERIAL: number;
    let RESET: number;
    let VERSION: number;
    let SET_BRIGHTNESS: number;
    let FRAMEBUFF: number;
    let SET_VIBRATION: number;
    let MCU: number;
    let DRAW: number;
    let TOUCH: number;
    let TOUCH_CT: number;
    let TOUCH_END: number;
    let TOUCH_END_CT: number;
}
export const DEFAULT_RECONNECT_INTERVAL: 3000;
export namespace HAPTIC {
    let SHORT: number;
    let MEDIUM: number;
    let LONG: number;
    let LOW: number;
    let SHORT_LOW: number;
    let SHORT_LOWER: number;
    let LOWER: number;
    let LOWEST: number;
    let DESCEND_SLOW: number;
    let DESCEND_MED: number;
    let DESCEND_FAST: number;
    let ASCEND_SLOW: number;
    let ASCEND_MED: number;
    let ASCEND_FAST: number;
    let REV_SLOWEST: number;
    let REV_SLOW: number;
    let REV_MED: number;
    let REV_FAST: number;
    let REV_FASTER: number;
    let REV_FASTEST: number;
    let RISE_FALL: number;
    let BUZZ: number;
    let RUMBLE5: number;
    let RUMBLE4: number;
    let RUMBLE3: number;
    let RUMBLE2: number;
    let RUMBLE1: number;
    let VERY_LONG: number;
}
export const MAX_BRIGHTNESS: 10;
